image: golang:latest

stages:
    - compile
    - intermediate
    - analysis
    - test
    - package
    - publish

TestStep:
    script:
        - go build main.go
        - go run main.go traildetect
    stage: intermediate
    artifacts:
        paths:
            - intermediate/*
        expire_in: '1 mos'
    allow_failure: true

TrailGeneration:
    image: 
        name: continuumio/miniconda3:latest
    stage: analysis
    script:
        - conda --version
        - conda install opencv scikit-learn matplotlib -y -q
        - python MatplotTag.py
    dependencies:
        - TestStep
    artifacts:
        paths:
            - output/*
        expire_in: '1 mos'
    allow_failure: true
    