package traffic

// Original input file format (as generated by darknet)
type TrailData_Source []TrailDatum_Source

type TrailDatum_Source struct {
	FrameID  int64           `json:"frame_id"`
	Filename string          `json:"filename"`
	Objects  []Object_Source `json:"objects"`
}

type Object_Source struct {
	ClassID             int                 `json:"class_id"`
	Name                Name                `json:"name"`
	RelativeCoordinates relativeCoordinates `json:"relative_coordinates"`
	Confidence          float64             `json:"confidence"`
}

// ---------------------------------------------------
